[system]
if_width = 1024

[module]
module = addllm_s_v2

[accelerator]
# in Hz
frequency = 1000000000
# in Bytes
Wgt_SRAM = 131072
Act_SRAM = 131072
Out_SRAM = 131072
a = 32
c = 32
high_prec = 8
low_prec = 4
